version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb_desafio_2
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: senha 
    networks:
      - desafio-network
  node:
    build:
      dockerfile: ./docker/node.dockerfile
      context: .
    image: node
    container_name: node_desafio_2
    ports:
      - "3000:3000"
    networks:
      - desafio-network
networks: 
  desafio-network:
    driver: bridge